version: '3'
services:
  consul:
    image: consul:latest
    environment:
      CONSUL_ALLOW_PRIVILEGED_PORTS: 53
      CONSUL_LOCAL_CONFIG: '{"domain": "consul", "ports": {"dns": 53}, "recursors": ["223.5.5.5", "8.8.8.8"], "http_config": {"response_headers": {"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "*", "Access-Control-Allow-Methods": "*"}}}'
    networks:
      custom_net:
        ipv4_address: 172.16.233.10
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8500:8500"

networks:
  custom_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.233.0/24